#!/bin/sh

echo "Running pre-commit hook..."

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rb$')

if [ -z "$files" ]; then
  echo "No Ruby files staged for commit."
  exit 0
fi

bin/rubocop $files

if [ $? -ne 0 ]; then
  echo "RuboCop failed. Commit aborted."
  exit 1
fi
