inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Lint/Debugger:
  Enabled: true

Rails/Output:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses

