inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - "db/migrate/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Lint/Debugger:
  Enabled: true

Rails/Output:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

