inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Include:
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - config/**/*.rb
    - lib/tasks/**/*.rake
    - vendor/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/TrailingWhitespace:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: space

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/BlockAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent


Lint/UselessAssignment:
  Enabled: true

Lint/Debugger:
  Enabled: true

Rails/Output:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInBlockArgs:
  EnforcedStyleForMultiline: consistent_comma
