services:
  db:
    image: mysql:8.0
    container_name: db_container
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ./
      dockerfile: .docker/app/Dockerfile
    environment:
      DATABASE_HOST: db_container
      DATABASE_NAME: database
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379
    volumes:
      - ./:/rails
    ports:
      - 3001:3001
    depends_on:
      - redis

  redis:
    container_name: redis_container
    image: redis:7.0
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    depends_on:
      - db

  # sidekiq:
  #   container_name: sidekiq_container
  #   build:
  #     dockerfile: .docker/sidekiq/Dockerfile
  #   environment:
  #     REDIS_URL: redis://redis:6379
  #   depends_on:
  #     - redis

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

