default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_ROOT") %>
  password: <%= ENV.fetch("DATABASE_ROOT_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test
  username: <%= ENV.fetch("DATABASE_ROOT") %>
  password: <%= ENV.fetch("DATABASE_ROOT_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") %>
    username: <%= ENV.fetch("DATABASE_ROOT") %>
    password: <%= ENV.fetch("DATABASE_ROOT_PASSWORD") %>
    host: <%= ENV.fetch("DATABASE_HOST") %>
