default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") %>
    username: <%= ENV.fetch("DATABASE_USER") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
